# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ollie/workspace/factory-game

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ollie/workspace/factory-game

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ollie/workspace/factory-game/CMakeFiles /home/ollie/workspace/factory-game//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ollie/workspace/factory-game/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named build.exec

# Build rule for target.
build.exec: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 build.exec
.PHONY : build.exec

# fast build rule for target.
build.exec/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.exec.dir/build.make CMakeFiles/build.exec.dir/build
.PHONY : build.exec/fast

include/SimplexNoise.o: include/SimplexNoise.cpp.o
.PHONY : include/SimplexNoise.o

# target to build an object file
include/SimplexNoise.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.exec.dir/build.make CMakeFiles/build.exec.dir/include/SimplexNoise.cpp.o
.PHONY : include/SimplexNoise.cpp.o

include/SimplexNoise.i: include/SimplexNoise.cpp.i
.PHONY : include/SimplexNoise.i

# target to preprocess a source file
include/SimplexNoise.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.exec.dir/build.make CMakeFiles/build.exec.dir/include/SimplexNoise.cpp.i
.PHONY : include/SimplexNoise.cpp.i

include/SimplexNoise.s: include/SimplexNoise.cpp.s
.PHONY : include/SimplexNoise.s

# target to generate assembly for a file
include/SimplexNoise.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.exec.dir/build.make CMakeFiles/build.exec.dir/include/SimplexNoise.cpp.s
.PHONY : include/SimplexNoise.cpp.s

include/glad.o: include/glad.c.o
.PHONY : include/glad.o

# target to build an object file
include/glad.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.exec.dir/build.make CMakeFiles/build.exec.dir/include/glad.c.o
.PHONY : include/glad.c.o

include/glad.i: include/glad.c.i
.PHONY : include/glad.i

# target to preprocess a source file
include/glad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.exec.dir/build.make CMakeFiles/build.exec.dir/include/glad.c.i
.PHONY : include/glad.c.i

include/glad.s: include/glad.c.s
.PHONY : include/glad.s

# target to generate assembly for a file
include/glad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.exec.dir/build.make CMakeFiles/build.exec.dir/include/glad.c.s
.PHONY : include/glad.c.s

src/engine/Input.o: src/engine/Input.cpp.o
.PHONY : src/engine/Input.o

# target to build an object file
src/engine/Input.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.exec.dir/build.make CMakeFiles/build.exec.dir/src/engine/Input.cpp.o
.PHONY : src/engine/Input.cpp.o

src/engine/Input.i: src/engine/Input.cpp.i
.PHONY : src/engine/Input.i

# target to preprocess a source file
src/engine/Input.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.exec.dir/build.make CMakeFiles/build.exec.dir/src/engine/Input.cpp.i
.PHONY : src/engine/Input.cpp.i

src/engine/Input.s: src/engine/Input.cpp.s
.PHONY : src/engine/Input.s

# target to generate assembly for a file
src/engine/Input.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.exec.dir/build.make CMakeFiles/build.exec.dir/src/engine/Input.cpp.s
.PHONY : src/engine/Input.cpp.s

src/engine/ResourceManager.o: src/engine/ResourceManager.cpp.o
.PHONY : src/engine/ResourceManager.o

# target to build an object file
src/engine/ResourceManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.exec.dir/build.make CMakeFiles/build.exec.dir/src/engine/ResourceManager.cpp.o
.PHONY : src/engine/ResourceManager.cpp.o

src/engine/ResourceManager.i: src/engine/ResourceManager.cpp.i
.PHONY : src/engine/ResourceManager.i

# target to preprocess a source file
src/engine/ResourceManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.exec.dir/build.make CMakeFiles/build.exec.dir/src/engine/ResourceManager.cpp.i
.PHONY : src/engine/ResourceManager.cpp.i

src/engine/ResourceManager.s: src/engine/ResourceManager.cpp.s
.PHONY : src/engine/ResourceManager.s

# target to generate assembly for a file
src/engine/ResourceManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.exec.dir/build.make CMakeFiles/build.exec.dir/src/engine/ResourceManager.cpp.s
.PHONY : src/engine/ResourceManager.cpp.s

src/engine/Scene.o: src/engine/Scene.cpp.o
.PHONY : src/engine/Scene.o

# target to build an object file
src/engine/Scene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.exec.dir/build.make CMakeFiles/build.exec.dir/src/engine/Scene.cpp.o
.PHONY : src/engine/Scene.cpp.o

src/engine/Scene.i: src/engine/Scene.cpp.i
.PHONY : src/engine/Scene.i

# target to preprocess a source file
src/engine/Scene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.exec.dir/build.make CMakeFiles/build.exec.dir/src/engine/Scene.cpp.i
.PHONY : src/engine/Scene.cpp.i

src/engine/Scene.s: src/engine/Scene.cpp.s
.PHONY : src/engine/Scene.s

# target to generate assembly for a file
src/engine/Scene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.exec.dir/build.make CMakeFiles/build.exec.dir/src/engine/Scene.cpp.s
.PHONY : src/engine/Scene.cpp.s

src/engine/Simplex.o: src/engine/Simplex.cpp.o
.PHONY : src/engine/Simplex.o

# target to build an object file
src/engine/Simplex.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.exec.dir/build.make CMakeFiles/build.exec.dir/src/engine/Simplex.cpp.o
.PHONY : src/engine/Simplex.cpp.o

src/engine/Simplex.i: src/engine/Simplex.cpp.i
.PHONY : src/engine/Simplex.i

# target to preprocess a source file
src/engine/Simplex.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.exec.dir/build.make CMakeFiles/build.exec.dir/src/engine/Simplex.cpp.i
.PHONY : src/engine/Simplex.cpp.i

src/engine/Simplex.s: src/engine/Simplex.cpp.s
.PHONY : src/engine/Simplex.s

# target to generate assembly for a file
src/engine/Simplex.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.exec.dir/build.make CMakeFiles/build.exec.dir/src/engine/Simplex.cpp.s
.PHONY : src/engine/Simplex.cpp.s

src/engine/View.o: src/engine/View.cpp.o
.PHONY : src/engine/View.o

# target to build an object file
src/engine/View.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.exec.dir/build.make CMakeFiles/build.exec.dir/src/engine/View.cpp.o
.PHONY : src/engine/View.cpp.o

src/engine/View.i: src/engine/View.cpp.i
.PHONY : src/engine/View.i

# target to preprocess a source file
src/engine/View.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.exec.dir/build.make CMakeFiles/build.exec.dir/src/engine/View.cpp.i
.PHONY : src/engine/View.cpp.i

src/engine/View.s: src/engine/View.cpp.s
.PHONY : src/engine/View.s

# target to generate assembly for a file
src/engine/View.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.exec.dir/build.make CMakeFiles/build.exec.dir/src/engine/View.cpp.s
.PHONY : src/engine/View.cpp.s

src/engine/ecs/Entity.o: src/engine/ecs/Entity.cpp.o
.PHONY : src/engine/ecs/Entity.o

# target to build an object file
src/engine/ecs/Entity.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.exec.dir/build.make CMakeFiles/build.exec.dir/src/engine/ecs/Entity.cpp.o
.PHONY : src/engine/ecs/Entity.cpp.o

src/engine/ecs/Entity.i: src/engine/ecs/Entity.cpp.i
.PHONY : src/engine/ecs/Entity.i

# target to preprocess a source file
src/engine/ecs/Entity.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.exec.dir/build.make CMakeFiles/build.exec.dir/src/engine/ecs/Entity.cpp.i
.PHONY : src/engine/ecs/Entity.cpp.i

src/engine/ecs/Entity.s: src/engine/ecs/Entity.cpp.s
.PHONY : src/engine/ecs/Entity.s

# target to generate assembly for a file
src/engine/ecs/Entity.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.exec.dir/build.make CMakeFiles/build.exec.dir/src/engine/ecs/Entity.cpp.s
.PHONY : src/engine/ecs/Entity.cpp.s

src/engine/utils/Texture.o: src/engine/utils/Texture.cpp.o
.PHONY : src/engine/utils/Texture.o

# target to build an object file
src/engine/utils/Texture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.exec.dir/build.make CMakeFiles/build.exec.dir/src/engine/utils/Texture.cpp.o
.PHONY : src/engine/utils/Texture.cpp.o

src/engine/utils/Texture.i: src/engine/utils/Texture.cpp.i
.PHONY : src/engine/utils/Texture.i

# target to preprocess a source file
src/engine/utils/Texture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.exec.dir/build.make CMakeFiles/build.exec.dir/src/engine/utils/Texture.cpp.i
.PHONY : src/engine/utils/Texture.cpp.i

src/engine/utils/Texture.s: src/engine/utils/Texture.cpp.s
.PHONY : src/engine/utils/Texture.s

# target to generate assembly for a file
src/engine/utils/Texture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.exec.dir/build.make CMakeFiles/build.exec.dir/src/engine/utils/Texture.cpp.s
.PHONY : src/engine/utils/Texture.cpp.s

src/game/components/BuildSystem.o: src/game/components/BuildSystem.cpp.o
.PHONY : src/game/components/BuildSystem.o

# target to build an object file
src/game/components/BuildSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.exec.dir/build.make CMakeFiles/build.exec.dir/src/game/components/BuildSystem.cpp.o
.PHONY : src/game/components/BuildSystem.cpp.o

src/game/components/BuildSystem.i: src/game/components/BuildSystem.cpp.i
.PHONY : src/game/components/BuildSystem.i

# target to preprocess a source file
src/game/components/BuildSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.exec.dir/build.make CMakeFiles/build.exec.dir/src/game/components/BuildSystem.cpp.i
.PHONY : src/game/components/BuildSystem.cpp.i

src/game/components/BuildSystem.s: src/game/components/BuildSystem.cpp.s
.PHONY : src/game/components/BuildSystem.s

# target to generate assembly for a file
src/game/components/BuildSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.exec.dir/build.make CMakeFiles/build.exec.dir/src/game/components/BuildSystem.cpp.s
.PHONY : src/game/components/BuildSystem.cpp.s

src/game/components/Chunk.o: src/game/components/Chunk.cpp.o
.PHONY : src/game/components/Chunk.o

# target to build an object file
src/game/components/Chunk.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.exec.dir/build.make CMakeFiles/build.exec.dir/src/game/components/Chunk.cpp.o
.PHONY : src/game/components/Chunk.cpp.o

src/game/components/Chunk.i: src/game/components/Chunk.cpp.i
.PHONY : src/game/components/Chunk.i

# target to preprocess a source file
src/game/components/Chunk.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.exec.dir/build.make CMakeFiles/build.exec.dir/src/game/components/Chunk.cpp.i
.PHONY : src/game/components/Chunk.cpp.i

src/game/components/Chunk.s: src/game/components/Chunk.cpp.s
.PHONY : src/game/components/Chunk.s

# target to generate assembly for a file
src/game/components/Chunk.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.exec.dir/build.make CMakeFiles/build.exec.dir/src/game/components/Chunk.cpp.s
.PHONY : src/game/components/Chunk.cpp.s

src/game/components/Inventory.o: src/game/components/Inventory.cpp.o
.PHONY : src/game/components/Inventory.o

# target to build an object file
src/game/components/Inventory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.exec.dir/build.make CMakeFiles/build.exec.dir/src/game/components/Inventory.cpp.o
.PHONY : src/game/components/Inventory.cpp.o

src/game/components/Inventory.i: src/game/components/Inventory.cpp.i
.PHONY : src/game/components/Inventory.i

# target to preprocess a source file
src/game/components/Inventory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.exec.dir/build.make CMakeFiles/build.exec.dir/src/game/components/Inventory.cpp.i
.PHONY : src/game/components/Inventory.cpp.i

src/game/components/Inventory.s: src/game/components/Inventory.cpp.s
.PHONY : src/game/components/Inventory.s

# target to generate assembly for a file
src/game/components/Inventory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.exec.dir/build.make CMakeFiles/build.exec.dir/src/game/components/Inventory.cpp.s
.PHONY : src/game/components/Inventory.cpp.s

src/game/components/Map.o: src/game/components/Map.cpp.o
.PHONY : src/game/components/Map.o

# target to build an object file
src/game/components/Map.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.exec.dir/build.make CMakeFiles/build.exec.dir/src/game/components/Map.cpp.o
.PHONY : src/game/components/Map.cpp.o

src/game/components/Map.i: src/game/components/Map.cpp.i
.PHONY : src/game/components/Map.i

# target to preprocess a source file
src/game/components/Map.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.exec.dir/build.make CMakeFiles/build.exec.dir/src/game/components/Map.cpp.i
.PHONY : src/game/components/Map.cpp.i

src/game/components/Map.s: src/game/components/Map.cpp.s
.PHONY : src/game/components/Map.s

# target to generate assembly for a file
src/game/components/Map.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.exec.dir/build.make CMakeFiles/build.exec.dir/src/game/components/Map.cpp.s
.PHONY : src/game/components/Map.cpp.s

src/game/components/MapGenerator.o: src/game/components/MapGenerator.cpp.o
.PHONY : src/game/components/MapGenerator.o

# target to build an object file
src/game/components/MapGenerator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.exec.dir/build.make CMakeFiles/build.exec.dir/src/game/components/MapGenerator.cpp.o
.PHONY : src/game/components/MapGenerator.cpp.o

src/game/components/MapGenerator.i: src/game/components/MapGenerator.cpp.i
.PHONY : src/game/components/MapGenerator.i

# target to preprocess a source file
src/game/components/MapGenerator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.exec.dir/build.make CMakeFiles/build.exec.dir/src/game/components/MapGenerator.cpp.i
.PHONY : src/game/components/MapGenerator.cpp.i

src/game/components/MapGenerator.s: src/game/components/MapGenerator.cpp.s
.PHONY : src/game/components/MapGenerator.s

# target to generate assembly for a file
src/game/components/MapGenerator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.exec.dir/build.make CMakeFiles/build.exec.dir/src/game/components/MapGenerator.cpp.s
.PHONY : src/game/components/MapGenerator.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.exec.dir/build.make CMakeFiles/build.exec.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.exec.dir/build.make CMakeFiles/build.exec.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.exec.dir/build.make CMakeFiles/build.exec.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

third-party/imgui/imgui.o: third-party/imgui/imgui.cpp.o
.PHONY : third-party/imgui/imgui.o

# target to build an object file
third-party/imgui/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.exec.dir/build.make CMakeFiles/build.exec.dir/third-party/imgui/imgui.cpp.o
.PHONY : third-party/imgui/imgui.cpp.o

third-party/imgui/imgui.i: third-party/imgui/imgui.cpp.i
.PHONY : third-party/imgui/imgui.i

# target to preprocess a source file
third-party/imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.exec.dir/build.make CMakeFiles/build.exec.dir/third-party/imgui/imgui.cpp.i
.PHONY : third-party/imgui/imgui.cpp.i

third-party/imgui/imgui.s: third-party/imgui/imgui.cpp.s
.PHONY : third-party/imgui/imgui.s

# target to generate assembly for a file
third-party/imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.exec.dir/build.make CMakeFiles/build.exec.dir/third-party/imgui/imgui.cpp.s
.PHONY : third-party/imgui/imgui.cpp.s

third-party/imgui/imgui_demo.o: third-party/imgui/imgui_demo.cpp.o
.PHONY : third-party/imgui/imgui_demo.o

# target to build an object file
third-party/imgui/imgui_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.exec.dir/build.make CMakeFiles/build.exec.dir/third-party/imgui/imgui_demo.cpp.o
.PHONY : third-party/imgui/imgui_demo.cpp.o

third-party/imgui/imgui_demo.i: third-party/imgui/imgui_demo.cpp.i
.PHONY : third-party/imgui/imgui_demo.i

# target to preprocess a source file
third-party/imgui/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.exec.dir/build.make CMakeFiles/build.exec.dir/third-party/imgui/imgui_demo.cpp.i
.PHONY : third-party/imgui/imgui_demo.cpp.i

third-party/imgui/imgui_demo.s: third-party/imgui/imgui_demo.cpp.s
.PHONY : third-party/imgui/imgui_demo.s

# target to generate assembly for a file
third-party/imgui/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.exec.dir/build.make CMakeFiles/build.exec.dir/third-party/imgui/imgui_demo.cpp.s
.PHONY : third-party/imgui/imgui_demo.cpp.s

third-party/imgui/imgui_draw.o: third-party/imgui/imgui_draw.cpp.o
.PHONY : third-party/imgui/imgui_draw.o

# target to build an object file
third-party/imgui/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.exec.dir/build.make CMakeFiles/build.exec.dir/third-party/imgui/imgui_draw.cpp.o
.PHONY : third-party/imgui/imgui_draw.cpp.o

third-party/imgui/imgui_draw.i: third-party/imgui/imgui_draw.cpp.i
.PHONY : third-party/imgui/imgui_draw.i

# target to preprocess a source file
third-party/imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.exec.dir/build.make CMakeFiles/build.exec.dir/third-party/imgui/imgui_draw.cpp.i
.PHONY : third-party/imgui/imgui_draw.cpp.i

third-party/imgui/imgui_draw.s: third-party/imgui/imgui_draw.cpp.s
.PHONY : third-party/imgui/imgui_draw.s

# target to generate assembly for a file
third-party/imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.exec.dir/build.make CMakeFiles/build.exec.dir/third-party/imgui/imgui_draw.cpp.s
.PHONY : third-party/imgui/imgui_draw.cpp.s

third-party/imgui/imgui_impl_glfw.o: third-party/imgui/imgui_impl_glfw.cpp.o
.PHONY : third-party/imgui/imgui_impl_glfw.o

# target to build an object file
third-party/imgui/imgui_impl_glfw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.exec.dir/build.make CMakeFiles/build.exec.dir/third-party/imgui/imgui_impl_glfw.cpp.o
.PHONY : third-party/imgui/imgui_impl_glfw.cpp.o

third-party/imgui/imgui_impl_glfw.i: third-party/imgui/imgui_impl_glfw.cpp.i
.PHONY : third-party/imgui/imgui_impl_glfw.i

# target to preprocess a source file
third-party/imgui/imgui_impl_glfw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.exec.dir/build.make CMakeFiles/build.exec.dir/third-party/imgui/imgui_impl_glfw.cpp.i
.PHONY : third-party/imgui/imgui_impl_glfw.cpp.i

third-party/imgui/imgui_impl_glfw.s: third-party/imgui/imgui_impl_glfw.cpp.s
.PHONY : third-party/imgui/imgui_impl_glfw.s

# target to generate assembly for a file
third-party/imgui/imgui_impl_glfw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.exec.dir/build.make CMakeFiles/build.exec.dir/third-party/imgui/imgui_impl_glfw.cpp.s
.PHONY : third-party/imgui/imgui_impl_glfw.cpp.s

third-party/imgui/imgui_impl_opengl3.o: third-party/imgui/imgui_impl_opengl3.cpp.o
.PHONY : third-party/imgui/imgui_impl_opengl3.o

# target to build an object file
third-party/imgui/imgui_impl_opengl3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.exec.dir/build.make CMakeFiles/build.exec.dir/third-party/imgui/imgui_impl_opengl3.cpp.o
.PHONY : third-party/imgui/imgui_impl_opengl3.cpp.o

third-party/imgui/imgui_impl_opengl3.i: third-party/imgui/imgui_impl_opengl3.cpp.i
.PHONY : third-party/imgui/imgui_impl_opengl3.i

# target to preprocess a source file
third-party/imgui/imgui_impl_opengl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.exec.dir/build.make CMakeFiles/build.exec.dir/third-party/imgui/imgui_impl_opengl3.cpp.i
.PHONY : third-party/imgui/imgui_impl_opengl3.cpp.i

third-party/imgui/imgui_impl_opengl3.s: third-party/imgui/imgui_impl_opengl3.cpp.s
.PHONY : third-party/imgui/imgui_impl_opengl3.s

# target to generate assembly for a file
third-party/imgui/imgui_impl_opengl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.exec.dir/build.make CMakeFiles/build.exec.dir/third-party/imgui/imgui_impl_opengl3.cpp.s
.PHONY : third-party/imgui/imgui_impl_opengl3.cpp.s

third-party/imgui/imgui_stdlib.o: third-party/imgui/imgui_stdlib.cpp.o
.PHONY : third-party/imgui/imgui_stdlib.o

# target to build an object file
third-party/imgui/imgui_stdlib.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.exec.dir/build.make CMakeFiles/build.exec.dir/third-party/imgui/imgui_stdlib.cpp.o
.PHONY : third-party/imgui/imgui_stdlib.cpp.o

third-party/imgui/imgui_stdlib.i: third-party/imgui/imgui_stdlib.cpp.i
.PHONY : third-party/imgui/imgui_stdlib.i

# target to preprocess a source file
third-party/imgui/imgui_stdlib.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.exec.dir/build.make CMakeFiles/build.exec.dir/third-party/imgui/imgui_stdlib.cpp.i
.PHONY : third-party/imgui/imgui_stdlib.cpp.i

third-party/imgui/imgui_stdlib.s: third-party/imgui/imgui_stdlib.cpp.s
.PHONY : third-party/imgui/imgui_stdlib.s

# target to generate assembly for a file
third-party/imgui/imgui_stdlib.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.exec.dir/build.make CMakeFiles/build.exec.dir/third-party/imgui/imgui_stdlib.cpp.s
.PHONY : third-party/imgui/imgui_stdlib.cpp.s

third-party/imgui/imgui_tables.o: third-party/imgui/imgui_tables.cpp.o
.PHONY : third-party/imgui/imgui_tables.o

# target to build an object file
third-party/imgui/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.exec.dir/build.make CMakeFiles/build.exec.dir/third-party/imgui/imgui_tables.cpp.o
.PHONY : third-party/imgui/imgui_tables.cpp.o

third-party/imgui/imgui_tables.i: third-party/imgui/imgui_tables.cpp.i
.PHONY : third-party/imgui/imgui_tables.i

# target to preprocess a source file
third-party/imgui/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.exec.dir/build.make CMakeFiles/build.exec.dir/third-party/imgui/imgui_tables.cpp.i
.PHONY : third-party/imgui/imgui_tables.cpp.i

third-party/imgui/imgui_tables.s: third-party/imgui/imgui_tables.cpp.s
.PHONY : third-party/imgui/imgui_tables.s

# target to generate assembly for a file
third-party/imgui/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.exec.dir/build.make CMakeFiles/build.exec.dir/third-party/imgui/imgui_tables.cpp.s
.PHONY : third-party/imgui/imgui_tables.cpp.s

third-party/imgui/imgui_widgets.o: third-party/imgui/imgui_widgets.cpp.o
.PHONY : third-party/imgui/imgui_widgets.o

# target to build an object file
third-party/imgui/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.exec.dir/build.make CMakeFiles/build.exec.dir/third-party/imgui/imgui_widgets.cpp.o
.PHONY : third-party/imgui/imgui_widgets.cpp.o

third-party/imgui/imgui_widgets.i: third-party/imgui/imgui_widgets.cpp.i
.PHONY : third-party/imgui/imgui_widgets.i

# target to preprocess a source file
third-party/imgui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.exec.dir/build.make CMakeFiles/build.exec.dir/third-party/imgui/imgui_widgets.cpp.i
.PHONY : third-party/imgui/imgui_widgets.cpp.i

third-party/imgui/imgui_widgets.s: third-party/imgui/imgui_widgets.cpp.s
.PHONY : third-party/imgui/imgui_widgets.s

# target to generate assembly for a file
third-party/imgui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build.exec.dir/build.make CMakeFiles/build.exec.dir/third-party/imgui/imgui_widgets.cpp.s
.PHONY : third-party/imgui/imgui_widgets.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... build.exec"
	@echo "... include/SimplexNoise.o"
	@echo "... include/SimplexNoise.i"
	@echo "... include/SimplexNoise.s"
	@echo "... include/glad.o"
	@echo "... include/glad.i"
	@echo "... include/glad.s"
	@echo "... src/engine/Input.o"
	@echo "... src/engine/Input.i"
	@echo "... src/engine/Input.s"
	@echo "... src/engine/ResourceManager.o"
	@echo "... src/engine/ResourceManager.i"
	@echo "... src/engine/ResourceManager.s"
	@echo "... src/engine/Scene.o"
	@echo "... src/engine/Scene.i"
	@echo "... src/engine/Scene.s"
	@echo "... src/engine/Simplex.o"
	@echo "... src/engine/Simplex.i"
	@echo "... src/engine/Simplex.s"
	@echo "... src/engine/View.o"
	@echo "... src/engine/View.i"
	@echo "... src/engine/View.s"
	@echo "... src/engine/ecs/Entity.o"
	@echo "... src/engine/ecs/Entity.i"
	@echo "... src/engine/ecs/Entity.s"
	@echo "... src/engine/utils/Texture.o"
	@echo "... src/engine/utils/Texture.i"
	@echo "... src/engine/utils/Texture.s"
	@echo "... src/game/components/BuildSystem.o"
	@echo "... src/game/components/BuildSystem.i"
	@echo "... src/game/components/BuildSystem.s"
	@echo "... src/game/components/Chunk.o"
	@echo "... src/game/components/Chunk.i"
	@echo "... src/game/components/Chunk.s"
	@echo "... src/game/components/Inventory.o"
	@echo "... src/game/components/Inventory.i"
	@echo "... src/game/components/Inventory.s"
	@echo "... src/game/components/Map.o"
	@echo "... src/game/components/Map.i"
	@echo "... src/game/components/Map.s"
	@echo "... src/game/components/MapGenerator.o"
	@echo "... src/game/components/MapGenerator.i"
	@echo "... src/game/components/MapGenerator.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... third-party/imgui/imgui.o"
	@echo "... third-party/imgui/imgui.i"
	@echo "... third-party/imgui/imgui.s"
	@echo "... third-party/imgui/imgui_demo.o"
	@echo "... third-party/imgui/imgui_demo.i"
	@echo "... third-party/imgui/imgui_demo.s"
	@echo "... third-party/imgui/imgui_draw.o"
	@echo "... third-party/imgui/imgui_draw.i"
	@echo "... third-party/imgui/imgui_draw.s"
	@echo "... third-party/imgui/imgui_impl_glfw.o"
	@echo "... third-party/imgui/imgui_impl_glfw.i"
	@echo "... third-party/imgui/imgui_impl_glfw.s"
	@echo "... third-party/imgui/imgui_impl_opengl3.o"
	@echo "... third-party/imgui/imgui_impl_opengl3.i"
	@echo "... third-party/imgui/imgui_impl_opengl3.s"
	@echo "... third-party/imgui/imgui_stdlib.o"
	@echo "... third-party/imgui/imgui_stdlib.i"
	@echo "... third-party/imgui/imgui_stdlib.s"
	@echo "... third-party/imgui/imgui_tables.o"
	@echo "... third-party/imgui/imgui_tables.i"
	@echo "... third-party/imgui/imgui_tables.s"
	@echo "... third-party/imgui/imgui_widgets.o"
	@echo "... third-party/imgui/imgui_widgets.i"
	@echo "... third-party/imgui/imgui_widgets.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

